export const MESSAGE = {
  SUCCESS: "Success",
  ERROR: "Error",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  UNAUTHORIZED: "Unauthorized",
  FORBIDDEN: "Forbidden",
  NOT_FOUND: "Not Found",
  BAD_REQUEST: "Bad Request",
  CONFLICT: "Conflict",
  UNPROCESSABLE_ENTITY: "Unprocessable Entity",
};

export const ORDER_VENDOR_STATUS = {
  PENDING: "PENDING",
  ACCEPTED: "ACCEPTED",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  FROZEN: "FROZEN",
  FINALIZED: "FINALIZED",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  IN_PROGRESS: "IN_PROGRESS",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
};

export const VENDOR_STATUS = {
  PENDING: "PENDING",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
  BLOCKED: "BLOCKED"
}